// Commercial craft the director and reviewer passes follow, condensed from a research pass over
// Google's ABCD research, Meta/TikTok mobile guidance, cinematography and category practice, and
// Veo's own prompting guide and known failure modes. Kept as plain rules so each one can be
// checked against a treatment.

export const CRAFT_RULES = `CRAFT RULES (how real commercials are made, adapted to AI video):
- Hook: the first 1–2 seconds must stop the scroll — open tight on a face mid-feeling or on one striking image, never on a logo, an establishing wide, or a slow build.
- Brand early: the brand's color should be present in the first shot (wardrobe, a prop, the set) so the film reads as this brand before the end card.
- One subject, one simple action, one motivated camera move per shot. The move has a reason (follow the action, reveal the payoff, bring us closer at the emotional beat).
- Shot sizes do jobs: wide sets the place, medium carries action, close-up carries emotion, macro carries texture. Emotion beats get close-ups.
- Lens: 24–35mm for spaces, 50mm for natural human scenes, 85mm+ with shallow depth for faces and products, macro for texture.
- Light is motivated by a real source (window, practical lamp, sun); a phone or laptop screen is never the key light on a face — AI video turns strong screen glow into sparkles and speckle on skin, so faces near screens stay lit by the window or room light; faces get soft key light with catchlights in the eyes; keep light direction consistent across shots in the same place.
- Performance is written as observable behavior (eyes drop to the page, a slow exhale, the pen stops, a small nod), never emotion words alone — AI video exaggerates "happy", "excited", "amazed". No posed smiles at camera.
- Continuity: same wardrobe, props, time of day and light direction across shots; keep screen direction consistent; vary shot sizes when cutting between shots of the same person.
- Software, apps and services have no body: never invent a device or gadget for them. Show them through the device people already use (a laptop or phone, screen angled away or seen as soft light on the face) and through what changes for the person.
- Cause and effect: the product appears before the change it causes, so the viewer sees why the turn happens. The product helps; the person wins — they finish the last action themselves (the student solves it, the runner finishes the run), the product is never a magic answer machine.
- Show the result of the product, not its interface: relief, time saved, the moment it clicks, the shared meal — the viewer should know what the product does for them.
- Never invent figures, rankings, prices, returns or claims in the shots — those belong only in the client's on-screen text and end card.
- Build every real product from the client's photo; keep labels turned away or soft if there is no photo; no rotation beyond ~30°.
- AI video limits: no readable text, UI, numbers or signage; no fine finger work in close-up; never show writing, handwriting or typing up close — show the gesture around it instead (the pen goes down, the notebook closes, she sits back); no one talking or lip-syncing; no crowds (at most 2–3 soft background figures); no fast complex motion (sprints, flips, ball contact); no big splashes or flying objects; one room per shot.
- Real places: generic architecture only — never an identifiable real university, company, landmark or crest, so the film never implies an affiliation.`;

// Category practice. The director applies whichever matches the brief (and ignores the rest).
export const CATEGORY_PLAYBOOKS = `CATEGORY PLAYBOOKS (apply the one that fits this brand):
- Food / restaurants: the food is the hero for at least half the film; backlight or side-light hot food so steam shows against a darker background; macro/100mm, shallow focus on the hero detail (gravy gloss, crisp edge, rice grains); one "money shot" action per shot (a pour, a tear, lifting the lid off the dum pot) in slow motion; warm color temperature, dark wood or brass surfaces; human delight as a small first-bite reaction (eyes close, a nod), never open-mouth chewing; background diners soft and few.
- Beauty / skincare: soft clamshell light on faces, catchlights in the eyes; real skin texture (visible pores, no retouching); one texture macro (a single serum drop, one swirl) in slow motion; application as one slow gesture (fingertip meets cheek), never fingers spreading product in detail; 85–100mm, shallow focus, clean neutral or brand-color background; a quiet private moment (morning light, a mirror), not posing; no before/after transformations; celebrate the full range of Indian skin tones.
- Apps / fintech: dramatize the before-state (the worry, the queue, the missed goal) and show the consequence of the app (relief, a shared win), never the screen — phones seen from the back or side, or a soft glow on the face; a single thumb tap at most, then cut to the result; warm, calm, steady camera for trust; no cash counting, card numbers, QR codes, charts or statements; physical metaphors for digital events (a small smile at a notification, not the notification).
- Real estate: sell the life, not the square feet — a family moment on the balcony, morning chai with a view; exteriors at golden or blue hour with interior lights on; interiors on a wide lens, camera slightly above eye level, verticals straight; slow gimbal moves (a push through a doorway, a slow slide past a window); one room per shot so architecture never warps; windows as the light source, practicals on.
- Sportswear / performance: one athlete per shot; low angles, backlight or rim light, contrasty look; one simple action in slow motion (a single stride, a foot strike, a deep breath before the run) — never sprints, dribbling or contact; effort, not glamour (dawn, sweat, empty streets); arc from doubt or ritual to effort to quiet triumph; brand color in the wardrobe; product macro on texture (mesh, midsole, tread) static or barely turning.
- Education: lead with the learner's feeling (the fear of a subject, the moment it clicks, a parent's pride), not the course list; the "click" is a close-up — eyes widen slightly, a small smile, the pen stops; real Indian study spaces; books, notebooks, whiteboards and screens always soft or angled away; parent-and-child two-shots as the trust signal; cast students as older teens or young adults.
- Physical products: light for the material (glass for highlights, metal for reflections, matte with soft top light); a surface that fits the tone (dark slate premium, warm wood natural, brand-color seamless for D2C); show it in context in a hand or a home at least once; the hero shot holds still or on a slow push for at least 2 seconds.`;
